[default]
src = 'contracts'
out = 'artifacts'
libs = ['lib']
remappings = [
    'ds-test/=lib/ds-test/src/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@rari-capital/=node_modules/@rari-capital/',
    'forge-std/=lib/forge-std/src/'
]

# See more config options https://github.com/gakonst/foundry/tree/master/config