export const flatNames = {
  head: 'head',
  maleheaddark: 'male dark head',
  femaleheadlight: 'female light head',
  malehead: 'male tan head',
  femalehead: 'female tan head',
  femaleheaddark: 'female dark head',
  maleheadlight: 'male light head',
  femaleheadzombie: 'female zombie head',
  maleheadalien: 'male alien head',
  femaleheadalien: 'female alien head',
  maleheadzombie: 'male zombie head',
  attributesNumber: 'number of attributes',
  facialhair: 'facial hair',
  bigblackbeard: 'big black beard',
  mustache: 'mustache',
  ponytailbeard: 'ponytail beard',
  bigbrownbeard: 'big brown beard',
  goatee: 'goatee',
  scruff: 'scruff',
  thinbeard: 'thin beard',
  handlebarmustache: 'handlebar mustache',
  smallbrownbeard: 'small brown beard',
  neckbeard: 'neck beard',
  accessories: 'accessories',
  hempnecklace: 'hemp necklace',
  earrings: 'earrings',
  glitter: 'glitter',
  donutmask: 'donut mask',
  glowband: 'glow band',
  mask: 'covid mask',
  glassesup: 'glasses up',
  headband: 'headband',
  unicorn: 'unicorn horn',
  donutscarf: 'donut scarf',
  hat: 'hat',
  visor: 'visor',
  baja: 'baja',
  knittedbeigehat: 'knitted beige hat',
  sailorhat: 'sailor hat',
  donuthat: 'donut hat',
  bajawhat: 'baja hat',
  knittedmaroonhat: 'knitted maroon hat',
  knittedberet: 'knitted beret',
  brimmedhat: 'brimmed hat',
  flatbrimhat: 'brimmed hat flat',
  rainbowforwardhat: 'forward rainbow hat',
  greenhoodie: 'green hoodie',
  rastahat: 'rasta hat',
  rainbowbackwardhat: 'backward rainbow hat ',
  visorwithhair: 'visor with hair',
  pieces: 'pieces',
  cig: 'cigarette',
  chillum: 'chillum',
  bowl: 'bowl',
  vape: 'vape',
  joint: 'joint',
  lsd: 'lsd',
  balloon: 'balloon',
  background: 'background',
  blue: 'blue background',
  'rainbow-squares': 'rainbow squares background',
  green: 'green background',
  purple: 'purple background',
  'colored-bands': 'colored bands background',
  'rainbow-bands': 'rainbow bands background',
  yellow: 'yellow background',
  'rainbow-diamonds': 'rainbow diamonds background',
  red: 'red background',
  'color-lines': 'colored lines background',
  'colored-stars': 'colored stars background',
  'color-worm': 'color worm',
  'show-lights': 'show lights',
  mouth: 'mouth',
  redlipstick: 'red lipstick',
  openmouth: 'mouth open',
  purplelipstick: 'purple lipstick',
  smile: 'smile',
  eyes: 'eyes',
  bigbluesunglasses: 'big blue sunglasses',
  blackrimmedsunglasses: 'black rimmed sunglasses',
  tiredeyes: 'tired eyes',
  smbloodshoteyes: 'small bloodshot eyes',
  greenrimmedsunglasses: 'green rimmed sunglasses',
  lgbloodshoteyes: 'large bloodshot eyes',
  bigredsunglasses: 'big red sunglasses',
  purpleeyeshadow: 'purple eyeshadow',
  aviatiors: 'aviators',
  crackedouteyes: 'cracked out eyes',
  blacksunglasses: 'black sunglasses',
  redrimmedsunglasses: 'red rimmed sunglasses',
  greysunglasses: 'grey sunglasses',
  largeflowersunglasses: 'flower sunglasses',
  hair: 'hair',
  ltbrowndreads: 'light brown dreads',
  blondehairwband: 'blonde hair with band',
  crazydkbrownhair: 'dark brown crazy hair',
  longdkbrownhair: 'dark brown long hair',
  catears: 'cat ears',
  brownhairwband: 'brown hair with band',
  blackdreads: 'black dreads',
  ltbeehive: 'light beehive',
  crazyblackhair: 'black crazy hair',
  crazyltbrownhair: 'light brown crazy hair',
  dkbrowndreads: 'dreads dark brown',
  longltbrownhair: 'long hair light brown',
  longblackhair: 'long hair black',
  flowerhair: 'flower hair',
  pinkhair: 'pink hair',
  dkbeehive: 'beehive dark',
  brownpigtails: 'pigtails brown',
  blackpigtails: 'pigtails black',
  dance: 'dance',
  dance4: 'wook dance 4',
  dance1: 'wook dance 1',
  dance2: 'wook dance 2',
  dance3: 'wook dance 3',
  dance5: 'wook dance 5',
  1: '1',
  2: '2',
  3: '3',
  4: '4',
  5: '5',
  6: '6',
};
